from datetime import datetime


def build_report(
    email_text,
    email_headers,
    urgency_found,
    links_found,
    greetings_found,
    grammar_found,
    fake_domains_found,
    blacklisted_found,
    header_findings,
    spoofing_found,
    suspicious_attachments,
    attachment_names,
    risk,
    score,
    indicators,
    tips
):
    lines = []
    lines.append("Phishing Analysis Report")
    lines.append("========================")
    lines.append(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%SZ')} UTC")
    lines.append("")

    lines.append("1. Executive Summary")
    lines.append("----------------------")
    lines.append(f"Overall Risk: {risk}")
    lines.append(f"Risk Score: {score}")
    lines.append("")

    lines.append("2. Indicators")
    lines.append("--------------")
    for indicator, found in indicators.items():
        lines.append(f"- {indicator}: {'YES' if found else 'NO'}")
    lines.append("")

    lines.append("3. Detailed Findings")
    lines.append("---------------------")
    if urgency_found:
        lines.append(f"Urgency keywords found: {', '.join(urgency_found)}")
    if links_found:
        lines.append(f"Suspicious links found: {', '.join(links_found)}")
    if fake_domains_found:
        lines.append(f"Potential fake domains: {', '.join(fake_domains_found)}")
    if blacklisted_found:
        lines.append(f"Blacklisted domains found: {', '.join(blacklisted_found)}")
    if greetings_found:
        lines.append(f"Generic greetings found: {', '.join(greetings_found)}")
    if grammar_found:
        lines.append(f"Grammar/spelling issues found: {', '.join(grammar_found)}")
    if header_findings:
        lines.append(f"Header authentication findings: {', '.join(header_findings)}")
    if spoofing_found:
        lines.append(f"Spoofing indicators: {', '.join(spoofing_found)}")
    if suspicious_attachments:
        lines.append(f"Suspicious attachments: {', '.join(suspicious_attachments)}")
    if attachment_names and not suspicious_attachments:
        lines.append(f"Attachments present: {', '.join(attachment_names)}")
    if not any([urgency_found, links_found, fake_domains_found, blacklisted_found, greetings_found, grammar_found, header_findings, spoofing_found, suspicious_attachments]):
        lines.append("No suspicious findings were detected in the analyzed email.")
    lines.append("")

    lines.append("4. Recommendations")
    lines.append("-------------------")
    if risk == "Phishing":
        lines.append("- Do not click any links or open attachments.")
        lines.append("- Verify the sender's email address and domain.")
        lines.append("- Report the email to your security team or email provider.")
        lines.append("- Avoid responding directly to the sender.")
    elif risk == "Suspicious":
        lines.append("- Exercise caution before interacting with this email.")
        lines.append("- Confirm unusual requests through a trusted channel.")
        lines.append("- Review the message for spelling and grammar mistakes.")
        lines.append("- Examine email headers for authentication failures.")
    else:
        lines.append("- The message appears low-risk, but still verify unknown senders.")
        lines.append("- Keep security software and authentication policies up to date.")
    lines.append("")

    lines.append("5. Email Content")
    lines.append("------------------")
    lines.append("Email headers:")
    lines.append(email_headers or "<no headers provided>")
    lines.append("")
    lines.append("Email body:")
    lines.append(email_text or "<no email body provided>")
    lines.append("")

    lines.append("6. Technical Notes")
    lines.append("---------------------")
    lines.append("This report was generated by the phishing detection application.")
    lines.append("Use the findings as a guide; if the email is suspicious, do not engage.")
    lines.append("")

    return "\n".join(lines)
